# Generated by Django 5.1.1 on 2024-09-25 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='club',
            field=models.CharField(db_index=True, default='Опыт не определен', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='exp',
            field=models.PositiveIntegerField(db_index=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, default='+996', max_length=17, null=True),
        ),
    ]
