# Generated by Django 5.1.1 on 2024-09-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255, verbose_name='enter title book')),
                ('author', models.CharField(max_length=255, verbose_name='author name')),
                ('image', models.ImageField(upload_to='post/', verbose_name='download picture')),
                ('pages', models.IntegerField(verbose_name='number of pages')),
                ('summary', models.TextField(verbose_name='write description')),
                ('url', models.URLField(verbose_name='write your news')),
                ('email', models.EmailField(max_length=254, verbose_name='write your email')),
                ('genre', models.CharField(choices=[('biography', 'Biography'), ('history', 'History'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy')], max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
