# Generated by Django 5.1.1 on 2024-09-12 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_post',
            name='url',
            field=models.URLField(verbose_name='write url of  news'),
        ),
        migrations.CreateModel(
            name='Reviewbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_book', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='books.books_post')),
            ],
        ),
    ]
