# Generated by Django 5.1.1 on 2024-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_post_url_reviewbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_post',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='tittle',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='enter title book'),
        ),
    ]
