# Generated by Django 5.1.1 on 2024-09-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_post_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_post',
            name='author',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, verbose_name='write your email'),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='genre',
            field=models.CharField(choices=[('biography', 'Biography'), ('history', 'History'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='image',
            field=models.ImageField(db_index=True, null=True, upload_to='post/', verbose_name='download picture'),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='pages',
            field=models.IntegerField(db_index=True, null=True, verbose_name='number of pages'),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='summary',
            field=models.TextField(db_index=True, null=True, verbose_name='write description'),
        ),
        migrations.AlterField(
            model_name='books_post',
            name='url',
            field=models.URLField(db_index=True, null=True, verbose_name='write url of  news'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='book_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='books.books_post'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='text_book',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
